import { StrictMode, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, BarChart3, Check, ChevronRight, CircleUserRound, ClipboardList, Landmark, LogOut, Plus, ShieldCheck, Users, Vote } from 'lucide-react'
import './styles.css'

const api = async (path, options = {}) => {
    const token = localStorage.getItem('campus-token')
    const response = await fetch(path, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } })
    const data = await response.json()
    if (response.status === 401) localStorage.removeItem('campus-token')
    if (!response.ok) throw new Error(data.error || 'Something went wrong')
    return data
}
const post = (path, body) => api(path, { method: 'POST', body: JSON.stringify(body) })

function App() {
    const [user, setUser] = useState(null)
    const [screen, setScreen] = useState('home')
    const [notice, setNotice] = useState('')
    useEffect(() => {
        api('/api/session').then(session => {
            setUser(session.role ? session : null)
            if (session.role === 'admin') setScreen('admin')
            if (session.role === 'voter') setScreen('voter')
        }).catch(() => { })
    }, [])
    const login = async (role, data) => { const result = await post(`/api/auth/${role}/login`, data); localStorage.setItem('campus-token', result.token); setUser(result); setScreen(role) }
    const logout = async () => { await post('/api/auth/logout', {}); localStorage.removeItem('campus-token'); setUser(null); setScreen('home') }
    return <div className="app-shell">
        <header className="topbar"><button className="brand" onClick={() => setScreen('home')}><span className="brand-mark"><Landmark size={17} /></span>Campus<span>Vote</span></button><div className="top-actions">{user?.role === 'admin' && <button className="quiet-button" onClick={() => setScreen('admin')}><BarChart3 size={16} /> Control room</button>}{user?.role === 'voter' && <button className="quiet-button" onClick={() => setScreen('voter')}><Vote size={16} /> My ballot</button>}{user && <button className="icon-button" title="Log out" onClick={logout}><LogOut size={18} /></button>}</div></header>
        {notice && <div className="notice">{notice}</div>}
        {screen === 'home' && <Home onVoter={() => setScreen('voter-login')} onAdmin={() => setScreen('admin-login')} />}
        {screen === 'voter-login' && <Login role="voter" onLogin={login} onBack={() => setScreen('home')} />}
        {screen === 'admin-login' && <Login role="admin" onLogin={login} onBack={() => setScreen('home')} />}
        {screen === 'voter' && user?.role === 'voter' && <VoterBallot onNotice={setNotice} />}
        {screen === 'admin' && user?.role === 'admin' && <Admin onNotice={setNotice} />}
    </div>
}

function Home({ onVoter, onAdmin }) {
    const [role, setRole] = useState('voter')
    const voterSelected = role === 'voter'
    return <main className="home-screen"><section className="hero interactive-hero"><div className="hero-copy"><div className="eyebrow-row"><span className="live-dot" /> Election access portal <span className="year-label">2026</span></div><h1>Make your voice<br /><em>official.</em></h1><p className="hero-lede">A secure, simple home for campus elections. Choose your path below to begin.</p><div className="role-switcher" aria-label="Choose your access type"><button className={`role-card ${voterSelected ? 'selected' : ''}`} onClick={() => setRole('voter')}><span className="role-icon"><Vote size={21} /></span><span><strong>Cast a ballot</strong><small>For registered voters</small></span><ChevronRight size={18} /></button><button className={`role-card ${!voterSelected ? 'selected' : ''}`} onClick={() => setRole('admin')}><span className="role-icon admin-icon"><ShieldCheck size={21} /></span><span><strong>Run an election</strong><small>For election administrators</small></span><ChevronRight size={18} /></button></div><button className="primary-button launch-button" onClick={voterSelected ? onVoter : onAdmin}>{voterSelected ? 'Enter my ballot' : 'Open admin control room'} <ArrowRight size={17} /></button></div><div className={`interactive-art ${voterSelected ? 'voter-mode' : 'admin-mode'}`}><div className="art-grid" /><div className="art-label">{voterSelected ? 'VOTER PORTAL' : 'ADMIN CONSOLE'}</div><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="access-badge">{voterSelected ? <Vote size={34} /> : <ShieldCheck size={34} />}<strong>{voterSelected ? 'READY TO VOTE' : 'CONTROL ROOM'}</strong><small>{voterSelected ? 'ONE VERIFIED BALLOT' : 'ELECTION OPERATIONS'}</small></div><div className="art-footer"><span>STATUS</span><strong><i /> SECURE</strong></div></div></section><section className="principles"><div><span className="number">01</span><h3>Verified access</h3><p>Only registered voters with an issued passcode can enter.</p></div><div><span className="number">02</span><h3>Private ballots</h3><p>The ballot never stores your identity alongside your choice.</p></div><div><span className="number">03</span><h3>Clear oversight</h3><p>Administrators get a live view of elections and participation.</p></div></section></main>
}

function Login({ role, onLogin, onBack }) { const [form, setForm] = useState({}); const [error, setError] = useState(''); const submit = async (event) => { event.preventDefault(); try { await onLogin(role, form) } catch (err) { setError(err.message) } }; return <main className="center-stage"><form className="login-panel" onSubmit={submit}><button type="button" className="back-link" onClick={onBack}>← Back home</button><span className="panel-icon">{role === 'admin' ? <ShieldCheck /> : <CircleUserRound />}</span><p className="kicker">{role === 'admin' ? 'Election administration' : 'Secure voter access'}</p><h1>{role === 'admin' ? 'Welcome back, admin.' : 'Find your ballot.'}</h1><p className="muted">{role === 'admin' ? 'Manage departments, voters, elections, and live results.' : 'Use the credentials issued by your electoral committee.'}</p>{role === 'admin' ? <Field label="Username" name="username" value={form.username} setForm={setForm} /> : <Field label="Voter ID" name="voter_id" value={form.voter_id} setForm={setForm} />}<Field label="Password" name="password" type="password" value={form.password} setForm={setForm} />{error && <div className="error">{error}</div>}<button className="primary-button wide">Continue <ArrowRight size={17} /></button></form></main> }
function Field({ label, name, type = 'text', value, setForm }) { return <label className="field"><span>{label}</span><input required type={type} value={value || ''} onChange={e => setForm(current => ({ ...current, [name]: e.target.value }))} /></label> }

function VoterBallot({ onNotice }) { const [data, setData] = useState(null); const [selected, setSelected] = useState(''); const [done, setDone] = useState(false); const [error, setError] = useState(''); useEffect(() => { api('/api/voter/ballot').then(setData).catch(err => setError(err.message)) }, []); if (error) return <main className="center-stage"><div className="empty-panel"><h2>{error}</h2><p>Sign out and try again with your issued voter credentials.</p></div></main>; if (!data) return <main className="center-stage"><p className="muted">Loading your ballot...</p></main>; if (done || data.alreadyVoted) return <main className="center-stage"><div className="success-panel"><span className="success-icon"><Check /></span><p className="kicker">Ballot recorded</p><h1>Thank you, {data.voter.full_name.split(' ')[0]}.</h1><p>Your vote has been securely recorded. The ballot box stores your choice without your identity.</p></div></main>; if (!data.election) return <main className="center-stage"><div className="empty-panel"><span className="panel-icon"><ClipboardList /></span><h1>Voting is not open yet.</h1><p>There is no active election for {data.voter.department_name}. Check back when your electoral admin opens the ballot.</p></div></main>; const submit = async () => { try { await post('/api/voter/vote', { candidate_id: selected }); setDone(true); onNotice('Your anonymous ballot was submitted.') } catch (err) { setError(err.message) } }; return <main className="ballot-page"><div className="section-heading"><div><p className="kicker">{data.election.department_name} department</p><h1>{data.election.title}</h1><p className="muted">Select one candidate. You can submit only once.</p></div><span className="live-tag"><i /> Voting open</span></div><div className="ballot-grid"><section className="ballot-card"><div className="card-topline"><span>Official ballot</span><span>01 / 01</span></div>{data.candidates.map(candidate => <label className={`candidate ${selected === String(candidate.id) ? 'selected' : ''}`} key={candidate.id}><input type="radio" name="candidate" value={candidate.id} onChange={e => setSelected(e.target.value)} /><span className="radio-mark">{selected === String(candidate.id) && <Check size={14} />}</span><span><strong>{candidate.full_name}</strong><small>{candidate.slogan || 'Candidate for departmental office'}</small></span></label>)}<button className="primary-button wide" disabled={!selected} onClick={submit}>Submit anonymous ballot <ArrowRight size={17} /></button>{error && <div className="error">{error}</div>}</section><aside className="privacy-note"><ShieldCheck size={23} /><h3>Your vote is private.</h3><p>We record that you participated separately from the ballot itself. Your candidate choice is never connected to your voter identity.</p></aside></div></main> }

function Admin({ onNotice }) { const [data, setData] = useState(null); const [error, setError] = useState(''); const [tab, setTab] = useState('elections'); const [showAdd, setShowAdd] = useState(false); const refresh = () => api('/api/admin/overview').then(result => { setData(result); setError('') }).catch(err => setError(err.message)); useEffect(() => { refresh() }, []); if (error) return <main className="center-stage"><div className="empty-panel"><span className="panel-icon"><ShieldCheck /></span><p className="kicker">Control room unavailable</p><h1>{error}</h1><p className="muted">Your session may have expired. Return home and sign in again.</p><button className="primary-button" onClick={() => window.location.reload()}>Try again <ArrowRight size={17} /></button></div></main>; if (!data) return <main className="center-stage"><p className="muted">Loading control room...</p></main>; const updateStatus = async (id, status) => { await post(`/api/admin/elections/${id}/status`, { status }); refresh(); onNotice(`Election ${status === 'active' ? 'opened' : 'closed'}.`) }; return <main className="admin-page"><div className="admin-header"><div><p className="kicker">Electoral administration</p><h1>Control room</h1><p className="muted">A live view of the elections under your care.</p></div><button className="primary-button" onClick={() => setShowAdd(!showAdd)}><Plus size={17} /> New election</button></div><div className="stat-grid"><Stat icon={<Landmark />} label="Departments" value={data.stats.departments} /><Stat icon={<Users />} label="Registered voters" value={data.stats.voters} /><Stat icon={<Vote />} label="Open elections" value={data.stats.active} /><Stat icon={<BarChart3 />} label="Ballots cast" value={data.stats.ballots} /></div><nav className="admin-tabs"><button className={tab === 'elections' ? 'active' : ''} onClick={() => setTab('elections')}>Elections</button><button className={tab === 'voters' ? 'active' : ''} onClick={() => setTab('voters')}>Voters</button></nav>{showAdd && <NewElection departments={data.departments} onDone={() => { setShowAdd(false); refresh(); onNotice('Election created as a draft.') }} />}{tab === 'elections' ? <ElectionTable elections={data.elections} updateStatus={updateStatus} /> : <VoterList onNotice={onNotice} />}</main> }
function Stat({ icon, label, value }) { return <div className="stat"><span>{icon}</span><strong>{value}</strong><small>{label}</small></div> }
function NewElection({ departments, onDone }) { const [form, setForm] = useState({}); const submit = async e => { e.preventDefault(); await post('/api/admin/elections', form); onDone() }; return <form className="inline-form" onSubmit={submit}><h3>Create election</h3><input required placeholder="Election title" onChange={e => setForm({ ...form, title: e.target.value })} /><select required onChange={e => setForm({ ...form, department_id: e.target.value })}><option value="">Choose department</option>{departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="primary-button">Create <ArrowRight size={16} /></button></form> }
function ElectionTable({ elections, updateStatus }) { return <section className="table-card"><div className="table-title"><h2>All elections</h2><span>{elections.length} total</span></div>{elections.length === 0 ? <p className="muted">No elections yet. Create your first one above.</p> : elections.map(election => <div className="election-row" key={election.id}><div className="election-mark"><Vote size={18} /></div><div className="election-name"><strong>{election.title}</strong><small>{election.department_name}</small></div><span className={`status ${election.status}`}>{election.status}</span><span className="row-stat"><strong>{election.candidate_count}</strong><small>candidates</small></span><span className="row-stat"><strong>{election.votes_count}</strong><small>ballots</small></span>{election.status === 'active' ? <button className="outline-button" onClick={() => updateStatus(election.id, 'closed')}>Close</button> : <button className="outline-button" onClick={() => updateStatus(election.id, 'active')}>Open</button>}</div>)}</section> }
function VoterList({ onNotice }) { const [data, setData] = useState(null); const [form, setForm] = useState({}); const [password, setPassword] = useState(''); const refresh = () => api('/api/admin/voters').then(setData); useEffect(() => { refresh() }, []); const submit = async e => { e.preventDefault(); const result = await post('/api/admin/voters', form); setPassword(result.password); setForm({}); refresh(); onNotice('Voter registered. Share the generated passcode securely.') }; if (!data) return <p className="muted">Loading voters...</p>; return <div className="voter-layout"><form className="small-form" onSubmit={submit}><h2>Register voter</h2><Field label="Voter ID" name="voter_id" value={form.voter_id} setForm={setForm} /><Field label="Full name" name="full_name" value={form.full_name} setForm={setForm} /><label className="field"><span>Department</span><select required value={form.department_id || ''} onChange={e => setForm({ ...form, department_id: e.target.value })}><option value="">Choose</option>{data.departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button className="primary-button wide">Register voter <Plus size={16} /></button>{password && <div className="credential"><small>One-time password</small><strong>{password}</strong></div>}</form><section className="table-card voter-table"><div className="table-title"><h2>Registered voters</h2><span>{data.voters.length} total</span></div>{data.voters.map(v => <div className="voter-row" key={v.id}><span className="avatar">{v.full_name.slice(0, 1)}</span><div><strong>{v.full_name}</strong><small>{v.voter_id} · {v.department_name}</small></div></div>)}</section></div> }

createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>)
